import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  UseGuards,
  Request,
} from '@nestjs/common';
import { AccessCodesService } from './access-codes.service';
import { CreateAccessCodeDto } from './dto/create-access-code.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';
import { UserRole } from '../users/entities/user.entity';

@Controller('access-codes')
@UseGuards(JwtAuthGuard, RolesGuard)
export class AccessCodesController {
  constructor(private readonly accessCodesService: AccessCodesService) {}

  @Post()
  @Roles(UserRole.ADMIN, UserRole.DISTRIBUTOR)
  create(@Request() req, @Body() createAccessCodeDto: CreateAccessCodeDto) {
    // Generated by the current user
    return this.accessCodesService.generateCode(
      createAccessCodeDto.targetRole,
      req.user._id, // User ID from JWT
      createAccessCodeDto.expiresInDays,
    );
  }

  @Get()
  @Roles(UserRole.ADMIN, UserRole.DISTRIBUTOR)
  findAll() {
    return this.accessCodesService.findAll();
  }
}
